### ISSUE TITLE
require commit access

### ISSUE THREAD

**Issue by christomonte11** [LucKy-4U/Firefox-Chrome-Folder#1]
Hi, coming on over from stackoverflow, requesting commit access, so that we can stay in contact.

My pleasure :-)

Regards, Micha

**PS**: Found that: <https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository>

**Comment by LucKy-4U** [comment]
hey man, I just sent you a collaborator invite. :))

**Comment by christomonte11** [comment]
Hi, thanks, think I'm in ...

I hesitated giving you any information about me, as you might have sensed, however, that was for a reason.

Could you please tell me 
1. What do you know about me (a) at stackoverflow == SO and (b) here at github == GH? Never mind, more is to come.
2. What would our "normal" way to ping one another be, right at this point without further metadata exchanged?

Regards, M.

**Comment by LucKy-4U** [comment]
ofcourse, I completely understand. That's why I didn't ask about anything other than your github account. :P

1. Well, I know nothing about you from either SO or GH. I know that you were willing to put atleast a day worth of time just to help me out so I just thought I should atleast keep in touch with you; that's about it.

2. Well, upto you to choose. I don't have any issue with just sending a message over here at github itself. Just like how we are chatting now but I don't have any issue with using any other mode of communication either. So you can choose whatever mode you are comfortable with. :)

**Comment by christomonte11** [comment]
Hi, thank you for your invitation. 

My 2nd name is Micha(el) that's what my friends are calling me, mostly. 

Today, I googled "write message on github" and found this <https://webapps.stackexchange.com/questions/29197/any-way-to-contact-a-user-on-github>, and therein <https://api.github.com/users/LucKy/events/public> with your github username set in for the xxxxxxxx part in the URL.

As you can see, there is some history revealed of us on github, and maybe in your case there's even an author entry with email and name sub-entries, which might be associated with your real name or email, I didn't scrutinize that further. 

However, I remember, that I set my github email to private, and if we set in christomonte11 instead of LucKy for the xxxxxxxx part, then, in my case, there is NO author entry with subsequent email and name sub-entries to be found there.

So maybe you want to check your github entries for privacy / security if all is fine and dandy for you.

I smell coffee in the air, I need to keep it short for now, but I'll be back ;-)

Regards. Micha

**Comment by LucKy-4U** [comment]
Hi Michael, Nice to meet you. :)
Yes, I saw your github profile, it looks like you are learning CSS and Javascript. :) Nice Work. :)
Author entry with an email? really? I had no idea; I don't really use github much. I had just created a profile long ago, but didn't really use it much. so I don't really remember what all stuff I did long ago and what all stuff is in there. :P 
at my workplace, we used SVN and other version control systems but never github. that's why I never used it a lot.

so well, that's pretty interesting stuff that you found out about me. I am impressed; well, find out what all you can. I want to see what all stuff you can pull off of it. :P
so you have found my email-id and my name, so tell me what it is. :)) and also tell me what other stuff you found out. :))

**Comment by christomonte11** [comment]
Hi, maybe I need to apologize.

See, I'm interested in privacy and security things, not so, say 5 years ago, but then more and more so. So, I don't  wanted to brag about my Sherlock-Holmesey skills, such would be ugly, wouldn't it, rather I wanted to tell you what I just learned from that stackoverflow post I showed you before, kinda to warn you to check the privacy settings of yours, because that author thing wasn't there if xxxxxxx==christomonte11 but if xxxxxxx=LucKy. That's all there is to it. BTW, you work as a dev.?

For tonight, I'll keep it short, see you soon,

Regards, M.

**Comment by LucKy-4U** [comment]
oh, Not at all, no need to apologize. I love Sherlock-Holmesey Skills, although the appropriate term should be Monsieur Lecoq skills, because that's whom Sir Arthur Conan Doyle copied. among others. :)) 
No man, it wouldn't be ugly at all. I wanna see what all you can pull on me. Show me your skills. Lets see how talented you are. :))
Well, I have been just as private and secure around 10 years ago, just as I am. :) Greed is a powerful motivator and that's why I simply don't trust people who are doing something for me just for money because they would always want more... :P 
that's why I usually prefer to slice and dice my tools myself instead of using the pre-packaged stuff. :))

**Comment by LucKy-4U** [comment]
also, I don't really mind if you were to find out my email or name or anything more so it's alright. You don't have to feel like you would be offending me or something just because you found out stuff about me.
I think I kept my email as private as well but if it still is visible then I would like to see. :)
that's why I am asking you to post as much info you can gather about me. :)
because it's alright if you found out about it all instead of some hacker with malign interest.
as you seem like a good guy and I don't think you would ever use any info about me to do anything malign, that's why. :))

**Comment by christomonte11** [comment]
Hi, thank you for your messages, read them carefully. So what can folks in the know find out about us.

Take a look at <https://api.github.com/users/LucKy/events/public> and search for "email" using the CTRL-F function of your browser. There! - one can get an email address, probably of yours? So, that's it from my current perspective what can be found out about you. 

Now substitute LucKy ---> christomonte11 in that URL and check again for "email" using CTRL-F. Nothing there, right? So that's what I discovered so far. Therefore I turned to you to kinda warn you, that maybe you want to set your email to private in github if such is important to you.

Next is, at <https://github.com/LucKy-4U> they show your persona with 3 traits, the user name LucKy, an "empty" avatar pic and, behold, your place "Germany", whereas in christomonte11 case it's just, well, christomonte11. So, again, might be github privacy settings making for the difference.

However, as you might know, I did clone your FF repository you gave me the link of in the first place. At my machine, using `git log` it just shows author Lucky and an automatic noreply github email address, so safe thing here.

That said, here's my bottom line: Maybe your name is Jared Harper and you live in Germany?

Disclaimer ;-)  I hereby confirm that I don't have other sources than those described so far.

Regards, Micha

**Comment by LucKy-4U** [comment]
hahaha, nice. you are smart. :) well, I just kept it like that so that other developers could see it. :) but yes, true, it's a bit of a privacy oversight. true. :)
And really appreciate your advice. makes perfect sense. :) You seem like a great guy. always so helpful. :) thanks for that. :) there are very few people left in this world who are like you. :)) so cheers to you. :) I wish more people in this world were like you. :))

**Comment by LucKy-4U** [comment]
but I really appreciate your advice. makes perfect sense. :) You seem like a great guy. always so helpful. :) thanks for that. :) there are very few people left in this world who are like you. :)) so cheers to you. :) I wish more people in this world were like you. :))

**Comment by christomonte11** [comment]
Thank you, however, it was the least I could do.

To be honest, in stackoverflow, I see things working both ways. One way is to help others, obviously. But another way, maybe isn't that obvious. See, I studied privacy & security of FF and TB in some detail all of December 2019 and so-so in January 2020.

After such a period, sometimes it comes to my mind to go to stackoverflow and see what questions others ask there about my recent studying project. Some of them might quite overlap with what I learned just days before and if I feel confident enough (not to bother others and steal their time) I try add my 2 cents to their cause.

Think a lot of people do this and a lot of people benefit from it.

Today, it's Acquisition-Monday over here, trying to find opportunities to get contract work. No fish yet. And you, have holiday or just having a break while on work?

Regards, M.

**Comment by LucKy-4U** [comment]
true, that's very smart. how old are you?
acquisition-monday? what's that?

and what did you learn about privacy and security of FF in 2 months? 

No, I have taken off from work to study for my exam.

**Comment by christomonte11** [comment]
Well, mozilla ghacks has github repos dedicated to FF and TB privacy & security preferences with wiki and such. Came across it quite some months back in the past, but figured then, that one day I wanted to study that. So some weeks around Xmas was the right time for me. It's time consuming because everybody needs to find her own compromise between privacy and functionality, you know. Hence, lots of iterations there ...

Age is probably double than yours. How's it going with your exam. Feel kinda confident?

**Comment by LucKy-4U** [comment]
true, makes perfect sense.

well, I am 29, are you 58? :P

not at all, but I have one month to study. :)) so lets hope that I would be when the time comes. Fingers crossed. :))

**Comment by LucKy-4U** [comment]
"Today, it's Acquisition-Monday over here, trying to find opportunities to get contract work. No fish yet."
You are a Theoretical Physicist? correct? so what kind of contract work are you looking for?

**Comment by christomonte11** [comment]
All correct, however, left academia >10 years ago, working as a software engineer these days.

And you, have plans for the time after your exams / graduation? Must need to chew lots of books?

**Comment by LucKy-4U** [comment]
oh, why did you leave academia?
so you are looking for contract work in web development? correct? searching online or at your local place?

na man, no plans for now. Will see when the comes. :)) well, how is your maths? :P being a theoretical physicist. your maths must be extremely strong? yea?

**Comment by christomonte11** [comment]
So-so, searching more broadly, could be embedded linux and such, too. Not hyper-specialized, has its good and its bad sides, yeah.

And yes, mathematics is the *sine qua non* condition if you're interested in such crazy things like theoretical physics. And you need a weird kind of patience others seem to lack. However my lack of patience is with non-igniting lasers and heinously non-coupling cables and other lab stuff. Couldn't do that ever. So I found my way ...

**Comment by LucKy-4U** [comment]
Interesting. But I would imagine you could make much more money following the theoretical physics line instead of doing part time software engineering stuff.

**Comment by LucKy-4U** [comment]
speaking from my life experience of 29 years, being a jack of all trades is never a good thing in today's world. Gotta be an expert in one thing or atleast that's what life taught me.
But everyone has their own life experiences which make them who they are. So yours could have been different. Everyone has their own opinions on such things I guess. :))

**Comment by christomonte11** [comment]
No-no, you're absolutely right. If you're able to stay focused, let it be that way. Me, too, I am trying to refocus things in recent months and I'm not done yet ...

**Comment by LucKy-4U** [comment]
also, the lesser the competition, the more money you make. considering the fact that theoretical physics is not something any young kid wants to do, I would imagine it would fetch you the most $$ for your time rather than the much more crowded field of software development, which nearly every just-born kid now a days wants to do. :P

**Comment by LucKy-4U** [comment]
but yes, I agree with you on staying focused and trying to refocus things. Very true.
where there is a will, there is a way. ;)) So anything is possible. :))

**Comment by LucKy-4U** [comment]
alright man, I wish you good luck with your job hunting. Remember, the early bird gets the worm. :))
and hey, I have one very small High School doubt about a small concept in Probability. which is going to be in my exams as well. If I were to ask you about it someday, would you be able to explain to me how it works? :)) only when you had a few minutes of your time, ofcourse.

**Comment by christomonte11** [comment]
Yes, that is one part of the equation. See, theoretical physics is a rather academical game, only the state is willing to pay at least something for people who are good at it. So, there is the first discrepancy here, what you have to give versus what you might get for it. It's not as rosy as you might think.

 I must admit, I never looked back to physics, and my colleagues haven't become happy men, you know. However, what is happening with the world now being eaten by crappy software, I find that a dramatic development to be a part of. I'm concerned with questions like why is software so crappy, how would one go about writing **really** good software and under what conditions might such be possible. So this is more or less my world now. I'll have a break now and sit down for an early dinner.

You need to excel in maths for your exam?

See you later, M.

**Comment by LucKy-4U** [comment]
yea, I do need maths as well but not very high level maths. just high school level but with surgical precision accuracy in calculation and concepts. :P
I am going for MBA, so that's why. :)) u see?
